Repository gangnamtestnet/progminer, pull requests merged in 2019-01, with the labels that each got.

#13 Drop CUDA 9.1 support and add CUDA 9.2 + 10
  .travis.yml
  scripts/install-cuda-ubuntu1604.sh
Labels: bug, enhancement, help wanted

#8 Minor optimizations
  libethash-cl/CLMiner.cpp
  libethash-cl/CLMiner.h
  libethash-cl/CLMiner_kernel.cl
  libethash-cuda/CUDAMiner.cpp
  libethcore/Farm.cpp
  libethcore/Miner.h
  progminer/main.cpp
Labels: enhancement, help wanted

#21 Extend no-new-work timeout for 10 days max
  libpoolprotocols/PoolManager.h
  progminer/main.cpp
Labels: enhancement

#22 Add CUDA 9.2 support for windows
  appveyor.yml
Labels: enhancement

#32 Cleanup #28
  libethash-cl/CLMiner_kernel.cl
Labels: enhancement

#33 Reduce default grid size for acceptable job swiitch time
  libethcore/Miner.h
Labels: bug, enhancement

#34 Preparation for kernel pre-calc and miscellaneous cleanup
  libdevcore/Worker.cpp
  libethash-cl/CLMiner.cpp
  libethash-cl/CLMiner.h
  libethash-cuda/CUDAMiner.cpp
  libethash-cuda/CUDAMiner.h
  libethcore/Miner.cpp
  libethcore/Miner.h
  libpoolprotocols/PoolManager.cpp
  libpoolprotocols/getwork/EthGetworkClient.cpp
  libpoolprotocols/stratum/EthStratumClient.cpp
Labels: enhancement

#35 Precompile opencl kernels to avoid delay at progpow period switch
  libethash-cl/CLMiner.cpp
  libethash-cl/CLMiner.h
  libethcore/Miner.h
Labels: enhancement

#36 Overlap CUDA compiles with mining by pre-compiling progpow kernels
  libdevcore/Worker.h
  libethash-cl/CLMiner.cpp
  libethash-cuda/CUDAMiner.cpp
  libethash-cuda/CUDAMiner.h
  libethcore/Miner.cpp
  libethcore/Miner.h
  libpoolprotocols/PoolManager.cpp
  libpoolprotocols/PoolManager.h
  libpoolprotocols/testing/SimulateClient.cpp
  libpoolprotocols/testing/SimulateClient.h
  progminer/main.cpp
Labels: enhancement

#37 Log cleanup
  libdevcore/Log.h
  libdevcore/Worker.cpp
  libethash-cl/CLMiner.cpp
  libethash-cuda/CUDAMiner.cpp
  libethcore/Farm.cpp
  libpoolprotocols/PoolManager.cpp
  libpoolprotocols/stratum/EthStratumClient.cpp
  progminer/main.cpp
Labels: enhancement
